version: '3.8'
services:
    db:
        image : mysql:8
        container_name : mysql
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: mysql_testing
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
